# config file version
apiVersion: 1

datasources:
  - name: mysql
    type: mysql
    url: $MYSQL_URL
    database: $MYSQL_DATABASE
    user: $MYSQL_USER
    secureJsonData:
      password: $MYSQL_PASSWORD
    editable: false
