# This action run e2e test for pull requests
name: test-e2e
on: [pull_request]
jobs:
  e2e-mysql:
    runs-on: ubuntu-latest
    services:
      db:
        image: mysql:8.0.26
        env:
          MYSQL_DATABASE: lake
          MYSQL_USER: merico
          MYSQL_PASSWORD: merico
          MYSQL_ROOT_PASSWORD: root
    container: mericodev/lake-builder:0.0.4
    steps:
      - uses: actions/checkout@v3
      - name: Test
        env:
          DB_URL: root:root@db:3306/lake?charset=utf8mb4&loc=Asia%2fShanghai&parseTime=True
        run: |
          cp .env.example .env
          make e2e-test
