on: [pull_request]
name: unit-test
jobs:
  test:
    strategy:
      matrix:
        #go-version: [1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: mericodev/lake-builder:0.0.4
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Unit tests
      run: |
        make unit-test
